### PR TITLE
Feat: Find Web3API endpoint implemented

### PR DESCRIPTION
**Pull request by cbrzn**

### CODE REVIEW

**Review by jeffscottward — COMMENTED** [review]
Awesome.
What is the Id? The ens?

"subdomain.open.web3.eth"?

**Comment by dOrgJelli** [comment]
If I understand the intention of this correctly, I think it'd be best to allow the endpoint to be called with a single URI (pointer or content) which could then be resolved on the backend to whatever package is using that URI. For example:
`service.io/apis/find/ens/some.domain.eth`
`service.io/apis/find/ipfs/QmHASH`
`service.io/apis/find/ens/rinkeby/another.domain.eth`

**Comment by jeffscottward** [comment]
I was just asking about how do you get a specific api from the backend.

If a user goes to
web3hub.org/apis/Uniswap

It would bring them to the Uniswap detail page.

Or for searching on the homepage search bar, need to send a request to grab matching apis based on the search string.

Basic web 2 stuff. Not sure what you were suggesting.

**Comment by dOrgJelli** [comment]
@jeffscottward so since each API has its own URIs, and multiple packages could be using the same semantic "name", doing something like `web3hub.app/apis/uniswap` won't work, because there's no consistent way of resolving what "uniswap" is. Instead we'd want to use a Web3API URI in the route. Something like this `web3hub.app/#/api/ens/uniswap.web3api.eth` where the Web3API URI comes after the `/api/` route. This is nice because it can be used for any Web3API that exists, for example: `web3hub.app/#/api/ipfs/QmMY_HASH`

**Comment by jeffscottward** [comment]
Ahhhh ok, understood.

I figured something like that but lacked the location path too. 

Ok will relay to Cesar. We were jus chatting about this.

**Pull request merged**
